export const permissions = [
  "tenant.read",
  "tenant.manage",
  "units.read",
  "units.manage",
  "memberships.read",
  "memberships.manage",
  "roles.read",
  "roles.manage",
  "audit.read",
  "occupational.read",
  "occupational.manage",
  "protocols.read",
  "protocols.manage",
  "pricing.read",
  "pricing.manage",
  "referrals.read",
  "referrals.manage",
  "schedule.read",
  "schedule.manage",
  "imports.manage",
  "encounters.read",
  "encounters.manage",
  "queues.read",
  "queues.manage",
  "display.read",
  "display.manage",
  "clinical.read",
  "triage.manage",
  "consultations.manage",
  "conclusions.manage",
  "clinical.reopen",
  "exams.read",
  "exams.manage",
  "documents.read",
  "documents.manage",
  "documents.sign",
  "documents.deliver",
  "finance.read",
  "finance.manage",
  "company_portal.read",
  "company_portal.manage",
  "integrations.read",
  "integrations.manage",
] as const;

export type Permission = (typeof permissions)[number];

export function isPermission(value: string): value is Permission {
  return permissions.some((permission) => permission === value);
}
